# Generated by Django 5.2.1 on 2025-06-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_followers_count', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_history', to='PageInfo.pageinfo')),
            ],
        ),
    ]
