# Generated by Django 5.2.1 on 2025-06-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0002_followerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerhistory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageInfo.pageinfo'),
        ),
        migrations.AlterField(
            model_name='followerhistory',
            name='page_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
